# ansible n1 -m file -a "path=/home/centos/n1_dir state=directory"
---
- name: Update n1 servers
  hosts: n1

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/n1_dir
      state: directory

  - name: Create Directory
    file:
      path: /home/centos/n1_dir_1
      state: directory    

- name: Update n2 servers
  hosts: n2

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir
      state: directory

  - name: Create Directory
    file:
      path: /home/centos/new_dir_2
      state: directory 

- name: Update group1 servers
  hosts: g1

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir_group
      state: directory

  - name: Create Directory
    file:
      path: /home/centos/new_dir_group2
      state: directory         
...
